name: Update Reading Statistics

on:
  schedule:
    # Run every hour
    - cron: "0 * * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Update Reading Statistics
        run: |
          curl -X POST '${{ secrets.SUPABASE_FUNCTIONS_URL }}/update-reading-stats' \
            -H 'Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}' \
            -H 'Content-Type: application/json'

      - name: Update Challenges
        run: |
          curl -X POST '${{ secrets.SUPABASE_FUNCTIONS_URL }}/update-challenges' \
            -H 'Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}' \
            -H 'Content-Type: application/json'

      - name: Update Missions
        run: |
          curl -X POST '${{ secrets.SUPABASE_FUNCTIONS_URL }}/update-missions' \
            -H 'Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}' \
            -H 'Content-Type: application/json'
